CSS_TO_TAILWIND_CONVERTER = ("for the given css, Along with the css identifier in the first line, i.e. class name or id, output a single string of tailwindcss classes that would style the same as the given css in the second line.\n"
"Example 1:\n"
"Input:\n"
".rtext {\n"
"  color: #ff0000;\n"
"}\n"
"Output:\n"
"rtext\n"
"text-red-500\n"
"Example 2:\n"
"Input:\n"
".bg-image-full {\n"
"  background-image: url('image.jpg');\n"
"  background-size: cover;\n"
"  background-position: center;\n"
"}\n"
"Output:\n"
"bg-image-full\n"
"bg-image bg-cover bg-center\n"
"----------\n"
"Generate the identifier name and a single string of tailwindcss classes that would style the same as the given css.\n"
"Input:\n"
"<<css>>"
"Output:\n"
)